apiVersion: v1
kind: Service
metadata: 
  name: nginx
  labels: 
    name: nginx
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 80
  selector: 
    name: nginx
    version: blue
  type: NodePort
    
